package javarominoes.model.music.song;

// Generated from contra-1.mid

import chiptunesynth.ChiptuneSong;
import chiptunesynth.Track;

// (Contra - Jungle / Stage 1, by Hidenori Maezawa)
// Sequenced by Anthony Bellissimo (1997)
public class ContraJungleSong implements ChiptuneSong {

  @Override
  public Track getLead() {
    Track t = new Track().withDefaults(LEAD_VOL, LEAD_DUTY);
    // Contra's lead is a wall of 6-frame sixteenths punctuated by big sustained
    // payoff notes (AS4/108, DS4/108). The 14-frame vibrato delay leaves the
    // sixteenth-note machine-gun runs razor-clean and reserves the wobble for
    // those held notes, so they bloom instead of sitting there as a flat tone.
    t.withVibrato(0.35, 5.5, 14);
    t.addNotes(
    C5, S, AS4, S, G4, S, F4, S, G4, S, F4, S,
    DS4, S, D4, S, DS4, S, D4, S, C4, S, AS3, S,
    AS3, S, G3, S, AS3, S, B3, S, C4, 38, R, DS + 1,
    G4, E, F4, S, G4, E, GS4, S, AS4, 108, C4, 38,
    R, DS + 1, G4, E, F4, S, G4, E, A4, S, DS4, 108,
    C4, 38, R, DS + 1, G4, E, F4, S, G4, E, GS4, S,
    AS4, 108, C4, 38, R, DS + 1, G4, E, F4, S, G4, E,
    A4, S, DS4, 108, G4, S, R, S, G4, E + 2, R, S - 2,
    A4, E + 2, R, S - 2, AS4, S, R, S, AS4, E, R, Q,
    A4, S, R, S, A4, E + 2, R, S - 2, AS4, E + 2, R, S - 2,
    C5, S, R, S, C5, E, AS4, S, C5, E + 2, R, S - 2,
    G4, S, R, S, G4, E + 2, R, S - 2, A4, E + 2, R, S - 2,
    AS4, S, R, S, AS4, E, R, Q, A4, S, R, S,
    A4, E + 2, R, S - 2, AS4, E + 2, R, S - 2, C5, DE + 1, R, S - 1,
    F5, DE + 1, R, S - 1, G5, S, F5, S, G5, S, F5, S,
    D6, S, C6, S, AS5, S, A5, S, G5, S, F5, S,
    G5, S, F5, S, D5, S, C5, S, D5, S, C5, S,
    G3, DE + 1, R, S - 1, G3, S, D4, E, DS4, S, G4, E,
    F4, E, DS4, S, D4, E, AS3, S, C3, S, C3, S,
    C3, S - 1, R, S + 1, C3, S, D3, E + 2, R, S - 2, DS3, E + 2,
    R, S - 2, C3, S, F3, S, G3, E + 2, R, S - 2, F3, DE + 1,
    R, S - 1, G3, S, A3, E + 2, R, S - 2, AS3, DE + 1, R, S - 1,
    C4, S, D4, E + 2, R, S - 2, DS4, DE + 1, R, S - 1, DS4, S,
    F4, E, G4, S, AS4, DE + 1, R, S - 1, A4, S, C4, S,
    DS4, S, F4, S, G4, S, F4, S, G4, S, C4, E,
    C4, S, DS4, S, F4, S, G4, E, AS4, S, A4, S,
    AS4, S, A4, E, F4, S, G4, S, F4, S, G4, S,
    C4, E, C4, S, DS4, S, F4, S, G4, E, AS4, S,
    A4, S, AS4, S, C5, E, D5, S, F3, DE + 1, R, S - 1,
    G3, S, A3, E + 2, R, S - 2, AS3, DE + 1, R, S - 1, C4, S,
    D4, E + 2, R, S - 2, DS4, S, DS4, S, DS4, E, DS4, S,
    F4, E, G4, S, AS4, DE + 1, R, S - 1, A4, DE + 1, R, S - 1,
    G4, S, G4, S, G4, S, G4, S - 1, R, S + 1, G4, S,
    G4, S, G4, S, G4, S, R, S, G4, S, R, S,
    F4, DE + 1, R, S - 1, DS4, S, DS4, S, DS4, S, DS4, S - 1,
    R, S + 1, DS4, S, DS4, S, DS4, S, DS4, S, R, S,
    DS4, S, R, S, F4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, F4, DE + 1, R, S - 1,
    DS4, S, DS4, S, DS4, S, DS4, S - 1, R, S + 1, DS4, S,
    F4, S, G4, S, A4, S, AS4, S, A4, S, R, S,
    F4, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, A4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, A4, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, A4, S, R, S,
    AS4, DE + 1, R, S - 1, C5, S, C5, S, C5, S, C5, S - 1,
    R, S + 1, C5, S, C5, S, C5, S, C5, S - 1, R, Q + 1,
    G3, S, C4, S, D4, S, DS4, S, D4, S, DS4, S,
    G3, E, G3, S, C4, S, D4, S, DS4, S, D4, S,
    DS4, S, G4, E, G4, S, F4, S, G4, S, DS4, S,
    D4, S, DS4, S, G3, E, G3, S, C4, T, R, T,
    D4, S, R, S, DS4, S, R, S, F4, S, R, S,
    G4, DE, C4, 38, R, DS + 1, G4, E, F4, S, G4, E,
    GS4, S, AS4, 108, C4, 38, R, DS + 1, G4, E, F4, S,
    G4, E, A4, S, DS4, 108, C4, 38, R, DS + 1, G4, E,
    F4, S, G4, E, GS4, S, AS4, 108, C4, 38, R, DS + 1,
    G4, E, F4, S, G4, E, A4, S, DS4, 108, G4, S,
    R, S, G4, E + 2, R, S - 2, A4, E + 2, R, S - 2, AS4, S,
    R, S, AS4, E, R, Q, A4, S, R, S, A4, E + 2,
    R, S - 2, AS4, E + 2, R, S - 2, C5, S, R, S, C5, E,
    AS4, S, C5, E + 2, R, S - 2, G4, S, R, S, G4, E + 2,
    R, S - 2, A4, E + 2, R, S - 2, AS4, S, R, S, AS4, E,
    R, Q, A4, S, R, S, A4, E + 2, R, S - 2, AS4, E + 2,
    R, S - 2, C5, DE + 1, R, S - 1, F5, DE + 1, R, S - 1, G5, S,
    F5, S, G5, S, F5, S, D6, S, C6, S, AS5, S,
    A5, S, G5, S, F5, S, G5, S, F5, S, D5, S,
    C5, S, D5, S, C5, S, G3, DE + 1, R, S - 1, G3, S,
    D4, E, DS4, S, G4, E, F4, E, DS4, S, D4, E,
    AS3, S, C3, S, C3, S, C3, S - 1, R, S + 1, C3, S,
    D3, E + 2, R, S - 2, DS3, E + 2, R, S - 2, C3, S, F3, S,
    G3, E + 2, R, S - 2, F3, DE + 1, R, S - 1, G3, S, A3, E + 2,
    R, S - 2, AS3, DE + 1, R, S - 1, C4, S, D4, E + 2, R, S - 2,
    DS4, DE + 1, R, S - 1, DS4, S, F4, E, G4, S, AS4, DE + 1,
    R, S - 1, A4, S, C4, S, DS4, S, F4, S, G4, S,
    F4, S, G4, S, C4, E, C4, S, DS4, S, F4, S,
    G4, E, AS4, S, A4, S, AS4, S, A4, E, F4, S,
    G4, S, F4, S, G4, S, C4, E, C4, S, DS4, S,
    F4, S, G4, E, AS4, S, A4, S, AS4, S, C5, E,
    D5, S, F3, DE + 1, R, S - 1, G3, S, A3, E + 2, R, S - 2,
    AS3, DE + 1, R, S - 1, C4, S, D4, E + 2, R, S - 2, DS4, S,
    DS4, S, DS4, E, DS4, S, F4, E, G4, S, AS4, DE + 1,
    R, S - 1, A4, DE + 1, R, S - 1, G4, S, G4, S, G4, S,
    G4, S - 1, R, S + 1, G4, S, G4, S, G4, S, G4, S,
    R, S, G4, S, R, S, F4, DE + 1, R, S - 1, DS4, S,
    DS4, S, DS4, S, DS4, S - 1, R, S + 1, DS4, S, DS4, S,
    DS4, S, DS4, S, R, S, DS4, S, R, S, F4, DE + 1,
    R, S - 1, G4, S, G4, S, G4, S, G4, S - 1, R, S + 1,
    G4, S, G4, S, G4, S, G4, S, R, S, G4, S,
    R, S, F4, DE + 1, R, S - 1, DS4, S, DS4, S, DS4, S,
    DS4, S - 1, R, S + 1, DS4, S, F4, S, G4, S, A4, S,
    AS4, S, A4, S, R, S, F4, DE + 1, R, S - 1, AS4, S,
    AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S, AS4, S,
    AS4, S, AS4, S, R, S, AS4, S, R, S, A4, DE + 1,
    R, S - 1, G4, S, G4, S, G4, S, G4, S - 1, R, S + 1,
    G4, S, G4, S, G4, S, G4, S, R, S, G4, S,
    R, S, A4, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S,
    AS4, S - 1, R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S,
    R, S, A4, S, R, S, AS4, DE + 1, R, S - 1, C5, S,
    C5, S, C5, S, C5, S - 1, R, S + 1, C5, S, C5, S,
    C5, S, C5, S - 1, R, Q + 1, G3, S, C4, S, D4, S,
    DS4, S, D4, S, DS4, S, G3, E, G3, S, C4, S,
    D4, S, DS4, S, D4, S, DS4, S, G4, E, G4, S,
    F4, S, G4, S, DS4, S, D4, S, DS4, S, G3, E,
    G3, S, C4, T, R, T, D4, S, R, S, DS4, S,
    R, S, F4, S, R, S, G4, DE, C4, 38, R, DS + 1,
    G4, E, F4, S, G4, E, GS4, S, AS4, 108, C4, 38,
    R, DS + 1, G4, E, F4, S, G4, E, A4, S, DS4, 108,
    C4, 38, R, DS + 1, G4, E, F4, S, G4, E, GS4, S,
    AS4, 108, C4, 38, R, DS + 1, G4, E, F4, S, G4, E,
    A4, S, DS4, 108, G4, S, R, S, G4, E + 2, R, S - 2,
    A4, E + 2, R, S - 2, AS4, S, R, S, AS4, E, R, Q,
    A4, S, R, S, A4, E + 2, R, S - 2, AS4, E + 2, R, S - 2,
    C5, S, R, S, C5, E, AS4, S, C5, E + 2, R, S - 2,
    G4, S, R, S, G4, E + 2, R, S - 2, A4, E + 2, R, S - 2,
    AS4, S, R, S, AS4, E, R, Q, A4, S, R, S,
    A4, E + 2, R, S - 2, AS4, E + 2, R, S - 2, C5, DE + 1, R, S - 1,
    F5, DE + 1, R, S - 1, G5, S, F5, S, G5, S, F5, S,
    D6, S, C6, S, AS5, S, A5, S, G5, S, F5, S,
    G5, S, F5, S, D5, S, C5, S, D5, S, C5, S,
    G3, DE + 1, R, S - 1, G3, S, D4, E, DS4, S, G4, E,
    F4, E, DS4, S, D4, E, AS3, S, C3, S, C3, S,
    C3, S - 1, R, S + 1, C3, S, D3, E + 2, R, S - 2, DS3, E + 2,
    R, S - 2, C3, S, F3, S, G3, E + 2, R, S - 2, F3, DE + 1,
    R, S - 1, G3, S, A3, E + 2, R, S - 2, AS3, DE + 1, R, S - 1,
    C4, S, D4, E + 2, R, S - 2, DS4, DE + 1, R, S - 1, DS4, S,
    F4, E, G4, S, AS4, DE + 1, R, S - 1, A4, S, C4, S,
    DS4, S, F4, S, G4, S, F4, S, G4, S, C4, E,
    C4, S, DS4, S, F4, S, G4, E, AS4, S, A4, S,
    AS4, S, A4, E, F4, S, G4, S, F4, S, G4, S,
    C4, E, C4, S, DS4, S, F4, S, G4, E, AS4, S,
    A4, S, AS4, S, C5, E, D5, S, F3, DE + 1, R, S - 1,
    G3, S, A3, E + 2, R, S - 2, AS3, DE + 1, R, S - 1, C4, S,
    D4, E + 2, R, S - 2, DS4, S, DS4, S, DS4, E, DS4, S,
    F4, E, G4, S, AS4, DE + 1, R, S - 1, A4, DE + 1, R, S - 1,
    G4, S, G4, S, G4, S, G4, S - 1, R, S + 1, G4, S,
    G4, S, G4, S, G4, S, R, S, G4, S, R, S,
    F4, DE + 1, R, S - 1, DS4, S, DS4, S, DS4, S, DS4, S - 1,
    R, S + 1, DS4, S, DS4, S, DS4, S, DS4, S, R, S,
    DS4, S, R, S, F4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, F4, DE + 1, R, S - 1,
    DS4, S, DS4, S, DS4, S, DS4, S - 1, R, S + 1, DS4, S,
    F4, S, G4, S, A4, S, AS4, S, A4, S, R, S,
    F4, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, A4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, A4, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, A4, S, R, S,
    AS4, DE + 1, R, S - 1, C5, S, C5, S, C5, S, C5, S - 1,
    R, S + 1, C5, S, C5, S, C5, S, C5, S - 1, R, Q + 1,
    G3, S, C4, S, D4, S, DS4, S, D4, S, DS4, S,
    G3, E, G3, S, C4, S, D4, S, DS4, S, D4, S,
    DS4, S, G4, E, G4, S, F4, S, G4, S, DS4, S,
    D4, S, DS4, S, G3, E, G3, S, C4, T, R, T,
    D4, S, R, S, DS4, S, R, S, F4, S, R, S,
    G4, DE, C4, 38, R, DS + 1, G4, E, F4, S, G4, E,
    GS4, S, AS4, 108, C4, 38, R, DS + 1, G4, E, F4, S,
    G4, E, A4, S, DS4, 108, C4, 38, R, DS + 1, G4, E,
    F4, S, G4, E, GS4, S, AS4, 108, C4, 38, R, DS + 1,
    G4, E, F4, S, G4, E, A4, S, DS4, 108, G4, S,
    R, S, G4, E + 2, R, S - 2, A4, E + 2, R, S - 2, AS4, S,
    R, S, AS4, E, R, Q, A4, S, R, S, A4, E + 2,
    R, S - 2, AS4, E + 2, R, S - 2, C5, S, R, S, C5, E,
    AS4, S, C5, E + 2, R, S - 2, G4, S, R, S, G4, E + 2,
    R, S - 2, A4, E + 2, R, S - 2, AS4, S, R, S, AS4, E,
    R, Q, A4, S, R, S, A4, E + 2, R, S - 2, AS4, E + 2,
    R, S - 2, C5, DE + 1, R, S - 1, F5, DE + 1, R, S - 1, G5, S,
    F5, S, G5, S, F5, S, D6, S, C6, S, AS5, S,
    A5, S, G5, S, F5, S, G5, S, F5, S, D5, S,
    C5, S, D5, S, C5, S, G3, DE + 1, R, S - 1, G3, S,
    D4, E, DS4, S, G4, E, F4, E, DS4, S, D4, E,
    AS3, S, C3, S, C3, S, C3, S - 1, R, S + 1, C3, S,
    D3, E + 2, R, S - 2, DS3, E + 2, R, S - 2, C3, S, F3, S,
    G3, E + 2, R, S - 2, F3, DE + 1, R, S - 1, G3, S, A3, E + 2,
    R, S - 2, AS3, DE + 1, R, S - 1, C4, S, D4, E + 2, R, S - 2,
    DS4, DE + 1, R, S - 1, DS4, S, F4, E, G4, S, AS4, DE + 1,
    R, S - 1, A4, S, C4, S, DS4, S, F4, S, G4, S,
    F4, S, G4, S, C4, E, C4, S, DS4, S, F4, S,
    G4, E, AS4, S, A4, S, AS4, S, A4, E, F4, S,
    G4, S, F4, S, G4, S, C4, E, C4, S, DS4, S,
    F4, S, G4, E, AS4, S, A4, S, AS4, S, C5, E,
    D5, S, F3, DE + 1, R, S - 1, G3, S, A3, E + 2, R, S - 2,
    AS3, DE + 1, R, S - 1, C4, S, D4, E + 2, R, S - 2, DS4, S,
    DS4, S, DS4, E, DS4, S, F4, E, G4, S, AS4, DE + 1,
    R, S - 1, A4, DE + 1, R, S - 1, G4, S, G4, S, G4, S,
    G4, S - 1, R, S + 1, G4, S, G4, S, G4, S, G4, S,
    R, S, G4, S, R, S, F4, DE + 1, R, S - 1, DS4, S,
    DS4, S, DS4, S, DS4, S - 1, R, S + 1, DS4, S, DS4, S,
    DS4, S, DS4, S, R, S, DS4, S, R, S, F4, DE + 1,
    R, S - 1, G4, S, G4, S, G4, S, G4, S - 1, R, S + 1,
    G4, S, G4, S, G4, S, G4, S, R, S, G4, S,
    R, S, F4, DE + 1, R, S - 1, DS4, S, DS4, S, DS4, S,
    DS4, S - 1, R, S + 1, DS4, S, F4, S, G4, S, A4, S,
    AS4, S, A4, S, R, S, F4, DE + 1, R, S - 1, AS4, S,
    AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S, AS4, S,
    AS4, S, AS4, S, R, S, AS4, S, R, S, A4, DE + 1,
    R, S - 1, G4, S, G4, S, G4, S, G4, S - 1, R, S + 1,
    G4, S, G4, S, G4, S, G4, S, R, S, G4, S,
    R, S, A4, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S,
    AS4, S - 1, R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S,
    R, S, A4, S, R, S, AS4, DE + 1, R, S - 1, C5, S,
    C5, S, C5, S, C5, S - 1, R, S + 1, C5, S, C5, S,
    C5, S, C5, S - 1, R, Q + 1, G3, S, C4, S, D4, S,
    DS4, S, D4, S, DS4, S, G3, E, G3, S, C4, S,
    D4, S, DS4, S, D4, S, DS4, S, G4, E, G4, S,
    F4, S, G4, S, DS4, S, D4, S, DS4, S, G3, E,
    G3, S, C4, T, R, T, D4, S, R, S, DS4, S,
    R, S, F4, S, R, S, G4, DE - 1
    );
    return t;
  }

  @Override
  public Track getHarmony() {
    Track t = new Track().withDefaults(HARMONY_VOL, HARMONY_DUTY);
    // Same treatment as the lead: the harmony shadows it in sixths/thirds and
    // shares its long held notes (DS5/108, GS4/108), so match the vibrato.
    t.withVibrato(0.3, 5.5, 14);
    t.addNotes(
    F5, S, DS5, S, C5, S, AS4, S, C5, S, AS4, S,
    GS4, S, G4, S, GS4, S, G4, S, F4, S, DS4, S,
    F4, S, C4, S, DS4, S, E4, S, F4, 38, R, DS + 1,
    C5, E, AS4, S, C5, E, D5, S, DS5, 108, F4, 38,
    R, DS + 1, C5, E, AS4, S, C5, E, D5, S, GS4, 108,
    F4, 38, R, DS + 1, C5, E, AS4, S, C5, E, D5, S,
    DS5, 108, F4, 38, R, DS + 1, C5, E, AS4, S, C5, E,
    D5, S, GS4, 108, C5, S, R, S, C5, E + 2, R, S - 2,
    D5, E + 2, R, S - 2, DS5, S, R, S, DS5, E, R, Q,
    D5, S, R, S, D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2,
    F5, S, R, S, F5, E, DS5, S, F5, E + 2, R, S - 2,
    C5, S, R, S, C5, E + 2, R, S - 2, D5, E + 2, R, S - 2,
    DS5, S, R, S, DS5, E, R, Q, D5, S, R, S,
    D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2, F5, DE + 1, R, S - 1,
    AS5, DE + 1, R, S - 1, AS5, S, A5, S, D6, S, C6, S,
    AS5, S, A5, S, G5, S, F5, S, G5, S, F5, S,
    D5, S, C5, S, D5, S, C5, S, AS4, S, A4, S,
    C4, DE + 1, R, S - 1, C4, S, D4, E, DS4, S, G4, E,
    F4, E, DS4, S, D4, E, AS3, S, C4, 77, R, DE + 1,
    A3, DE + 1, R, S - 1, AS3, S, C4, E + 2, R, S - 2, D4, DE + 1,
    R, S - 1, DS4, S, F4, E + 2, R, S - 2, G4, DE + 1, R, S - 1,
    G4, S, A4, E, AS4, S, D5, DE + 1, R, S - 1, C5, S,
    C4, S, DS4, S, F4, S - 1, R, 97, G4, 77, R, DE + 1,
    A3, DE + 1, R, S - 1, AS3, S, C4, E + 2, R, S - 2, D4, DE + 1,
    R, S - 1, DS4, S, F4, E + 2, R, S - 2, G4, S, G4, S,
    G4, E, G4, S, A4, E, AS4, S, D5, DE + 1, R, S - 1,
    C5, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, A4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, A4, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, AS4, S, R, S,
    A4, DE + 1, R, S - 1, G4, S, G4, S, G4, S, G4, S - 1,
    R, S + 1, G4, S, A4, S, AS4, S, C5, S, D5, S,
    C5, S, R, S, A4, DE + 1, R, S - 1, D5, S, D5, S,
    D5, S, D5, S - 1, R, S + 1, D5, S, D5, S, D5, S,
    D5, S, R, S, D5, S, R, S, C5, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, AS4, S, R, S,
    C5, DE + 1, R, S - 1, D5, S, D5, S, D5, S, D5, S - 1,
    R, S + 1, D5, S, D5, S, D5, S, D5, S, R, S,
    D5, S, R, S, DS5, DE + 1, R, S - 1, F5, S, F5, S,
    F5, S, F5, S - 1, R, S + 1, F5, S, F5, S, F5, S,
    F5, S - 1, R, Q + 1, C4, S, DS4, S, F4, S, G4, S,
    F4, S, G4, S, C4, E, C4, S, DS4, S, F4, S,
    G4, S, F4, S, G4, S, AS4, E, AS4, S, A4, S,
    AS4, S, G4, S, F4, S, G4, S, C4, E, C4, S,
    DS4, S, F4, S, R, S, G4, S, R, S, A4, S,
    R, S, AS4, DE, F4, 38, R, DS + 1, C5, E, AS4, S,
    C5, E, D5, S, DS5, 108, F4, 38, R, DS + 1, C5, E,
    AS4, S, C5, E, D5, S, GS4, 108, F4, 38, R, DS + 1,
    C5, E, AS4, S, C5, E, D5, S, DS5, 108, F4, 38,
    R, DS + 1, C5, E, AS4, S, C5, E, D5, S, GS4, 108,
    C5, S, R, S, C5, E + 2, R, S - 2, D5, E + 2, R, S - 2,
    DS5, S, R, S, DS5, E, R, Q, D5, S, R, S,
    D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2, F5, S, R, S,
    F5, E, DS5, S, F5, E + 2, R, S - 2, C5, S, R, S,
    C5, E + 2, R, S - 2, D5, E + 2, R, S - 2, DS5, S, R, S,
    DS5, E, R, Q, D5, S, R, S, D5, E + 2, R, S - 2,
    DS5, E + 2, R, S - 2, F5, DE + 1, R, S - 1, AS5, DE + 1, R, S - 1,
    AS5, S, A5, S, D6, S, C6, S, AS5, S, A5, S,
    G5, S, F5, S, G5, S, F5, S, D5, S, C5, S,
    D5, S, C5, S, AS4, S, A4, S, C4, DE + 1, R, S - 1,
    C4, S, D4, E, DS4, S, G4, E, F4, E, DS4, S,
    D4, E, AS3, S, C4, 77, R, DE + 1, A3, DE + 1, R, S - 1,
    AS3, S, C4, E + 2, R, S - 2, D4, DE + 1, R, S - 1, DS4, S,
    F4, E + 2, R, S - 2, G4, DE + 1, R, S - 1, G4, S, A4, E,
    AS4, S, D5, DE + 1, R, S - 1, C5, S, C4, S, DS4, S,
    F4, S - 1, R, 97, G4, 77, R, DE + 1, A3, DE + 1, R, S - 1,
    AS3, S, C4, E + 2, R, S - 2, D4, DE + 1, R, S - 1, DS4, S,
    F4, E + 2, R, S - 2, G4, S, G4, S, G4, E, G4, S,
    A4, E, AS4, S, D5, DE + 1, R, S - 1, C5, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, AS4, S, R, S,
    A4, DE + 1, R, S - 1, G4, S, G4, S, G4, S, G4, S - 1,
    R, S + 1, G4, S, G4, S, G4, S, G4, S, R, S,
    G4, S, R, S, A4, DE + 1, R, S - 1, AS4, S, AS4, S,
    AS4, S, AS4, S - 1, R, S + 1, AS4, S, AS4, S, AS4, S,
    AS4, S, R, S, AS4, S, R, S, A4, DE + 1, R, S - 1,
    G4, S, G4, S, G4, S, G4, S - 1, R, S + 1, G4, S,
    A4, S, AS4, S, C5, S, D5, S, C5, S, R, S,
    A4, DE + 1, R, S - 1, D5, S, D5, S, D5, S, D5, S - 1,
    R, S + 1, D5, S, D5, S, D5, S, D5, S, R, S,
    D5, S, R, S, C5, DE + 1, R, S - 1, AS4, S, AS4, S,
    AS4, S, AS4, S - 1, R, S + 1, AS4, S, AS4, S, AS4, S,
    AS4, S, R, S, AS4, S, R, S, C5, DE + 1, R, S - 1,
    D5, S, D5, S, D5, S, D5, S - 1, R, S + 1, D5, S,
    D5, S, D5, S, D5, S, R, S, D5, S, R, S,
    DS5, DE + 1, R, S - 1, F5, S, F5, S, F5, S, F5, S - 1,
    R, S + 1, F5, S, F5, S, F5, S, F5, S - 1, R, Q + 1,
    C4, S, DS4, S, F4, S, G4, S, F4, S, G4, S,
    C4, E, C4, S, DS4, S, F4, S, G4, S, F4, S,
    G4, S, AS4, E, AS4, S, A4, S, AS4, S, G4, S,
    F4, S, G4, S, C4, E, C4, S, DS4, S, F4, S,
    R, S, G4, S, R, S, A4, S, R, S, AS4, DE,
    F4, 38, R, DS + 1, C5, E, AS4, S, C5, E, D5, S,
    DS5, 108, F4, 38, R, DS + 1, C5, E, AS4, S, C5, E,
    D5, S, GS4, 108, F4, 38, R, DS + 1, C5, E, AS4, S,
    C5, E, D5, S, DS5, 108, F4, 38, R, DS + 1, C5, E,
    AS4, S, C5, E, D5, S, GS4, 108, C5, S, R, S,
    C5, E + 2, R, S - 2, D5, E + 2, R, S - 2, DS5, S, R, S,
    DS5, E, R, Q, D5, S, R, S, D5, E + 2, R, S - 2,
    DS5, E + 2, R, S - 2, F5, S, R, S, F5, E, DS5, S,
    F5, E + 2, R, S - 2, C5, S, R, S, C5, E + 2, R, S - 2,
    D5, E + 2, R, S - 2, DS5, S, R, S, DS5, E, R, Q,
    D5, S, R, S, D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2,
    F5, DE + 1, R, S - 1, AS5, DE + 1, R, S - 1, AS5, S, A5, S,
    D6, S, C6, S, AS5, S, A5, S, G5, S, F5, S,
    G5, S, F5, S, D5, S, C5, S, D5, S, C5, S,
    AS4, S, A4, S, C4, DE + 1, R, S - 1, C4, S, D4, E,
    DS4, S, G4, E, F4, E, DS4, S, D4, E, AS3, S,
    C4, 77, R, DE + 1, A3, DE + 1, R, S - 1, AS3, S, C4, E + 2,
    R, S - 2, D4, DE + 1, R, S - 1, DS4, S, F4, E + 2, R, S - 2,
    G4, DE + 1, R, S - 1, G4, S, A4, E, AS4, S, D5, DE + 1,
    R, S - 1, C5, S, C4, S, DS4, S, F4, S - 1, R, 97,
    G4, 77, R, DE + 1, A3, DE + 1, R, S - 1, AS3, S, C4, E + 2,
    R, S - 2, D4, DE + 1, R, S - 1, DS4, S, F4, E + 2, R, S - 2,
    G4, S, G4, S, G4, E, G4, S, A4, E, AS4, S,
    D5, DE + 1, R, S - 1, C5, DE + 1, R, S - 1, AS4, S, AS4, S,
    AS4, S, AS4, S - 1, R, S + 1, AS4, S, AS4, S, AS4, S,
    AS4, S, R, S, AS4, S, R, S, A4, DE + 1, R, S - 1,
    G4, S, G4, S, G4, S, G4, S - 1, R, S + 1, G4, S,
    G4, S, G4, S, G4, S, R, S, G4, S, R, S,
    A4, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, A4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, A4, S, AS4, S,
    C5, S, D5, S, C5, S, R, S, A4, DE + 1, R, S - 1,
    D5, S, D5, S, D5, S, D5, S - 1, R, S + 1, D5, S,
    D5, S, D5, S, D5, S, R, S, D5, S, R, S,
    C5, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, C5, DE + 1, R, S - 1, D5, S, D5, S,
    D5, S, D5, S - 1, R, S + 1, D5, S, D5, S, D5, S,
    D5, S, R, S, D5, S, R, S, DS5, DE + 1, R, S - 1,
    F5, S, F5, S, F5, S, F5, S - 1, R, S + 1, F5, S,
    F5, S, F5, S, F5, S - 1, R, Q + 1, C4, S, DS4, S,
    F4, S, G4, S, F4, S, G4, S, C4, E, C4, S,
    DS4, S, F4, S, G4, S, F4, S, G4, S, AS4, E,
    AS4, S, A4, S, AS4, S, G4, S, F4, S, G4, S,
    C4, E, C4, S, DS4, S, F4, S, R, S, G4, S,
    R, S, A4, S, R, S, AS4, DE, F4, 38, R, DS + 1,
    C5, E, AS4, S, C5, E, D5, S, DS5, 108, F4, 38,
    R, DS + 1, C5, E, AS4, S, C5, E, D5, S, GS4, 108,
    F4, 38, R, DS + 1, C5, E, AS4, S, C5, E, D5, S,
    DS5, 108, F4, 38, R, DS + 1, C5, E, AS4, S, C5, E,
    D5, S, GS4, 108, C5, S, R, S, C5, E + 2, R, S - 2,
    D5, E + 2, R, S - 2, DS5, S, R, S, DS5, E, R, Q,
    D5, S, R, S, D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2,
    F5, S, R, S, F5, E, DS5, S, F5, E + 2, R, S - 2,
    C5, S, R, S, C5, E + 2, R, S - 2, D5, E + 2, R, S - 2,
    DS5, S, R, S, DS5, E, R, Q, D5, S, R, S,
    D5, E + 2, R, S - 2, DS5, E + 2, R, S - 2, F5, DE + 1, R, S - 1,
    AS5, DE + 1, R, S - 1, AS5, S, A5, S, D6, S, C6, S,
    AS5, S, A5, S, G5, S, F5, S, G5, S, F5, S,
    D5, S, C5, S, D5, S, C5, S, AS4, S, A4, S,
    C4, DE + 1, R, S - 1, C4, S, D4, E, DS4, S, G4, E,
    F4, E, DS4, S, D4, E, AS3, S, C4, 77, R, DE + 1,
    A3, DE + 1, R, S - 1, AS3, S, C4, E + 2, R, S - 2, D4, DE + 1,
    R, S - 1, DS4, S, F4, E + 2, R, S - 2, G4, DE + 1, R, S - 1,
    G4, S, A4, E, AS4, S, D5, DE + 1, R, S - 1, C5, S,
    C4, S, DS4, S, F4, S - 1, R, 97, G4, 77, R, DE + 1,
    A3, DE + 1, R, S - 1, AS3, S, C4, E + 2, R, S - 2, D4, DE + 1,
    R, S - 1, DS4, S, F4, E + 2, R, S - 2, G4, S, G4, S,
    G4, E, G4, S, A4, E, AS4, S, D5, DE + 1, R, S - 1,
    C5, DE + 1, R, S - 1, AS4, S, AS4, S, AS4, S, AS4, S - 1,
    R, S + 1, AS4, S, AS4, S, AS4, S, AS4, S, R, S,
    AS4, S, R, S, A4, DE + 1, R, S - 1, G4, S, G4, S,
    G4, S, G4, S - 1, R, S + 1, G4, S, G4, S, G4, S,
    G4, S, R, S, G4, S, R, S, A4, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, AS4, S, R, S,
    A4, DE + 1, R, S - 1, G4, S, G4, S, G4, S, G4, S - 1,
    R, S + 1, G4, S, A4, S, AS4, S, C5, S, D5, S,
    C5, S, R, S, A4, DE + 1, R, S - 1, D5, S, D5, S,
    D5, S, D5, S - 1, R, S + 1, D5, S, D5, S, D5, S,
    D5, S, R, S, D5, S, R, S, C5, DE + 1, R, S - 1,
    AS4, S, AS4, S, AS4, S, AS4, S - 1, R, S + 1, AS4, S,
    AS4, S, AS4, S, AS4, S, R, S, AS4, S, R, S,
    C5, DE + 1, R, S - 1, D5, S, D5, S, D5, S, D5, S - 1,
    R, S + 1, D5, S, D5, S, D5, S, D5, S, R, S,
    D5, S, R, S, DS5, DE + 1, R, S - 1, F5, S, F5, S,
    F5, S, F5, S - 1, R, S + 1, F5, S, F5, S, F5, S,
    F5, S - 1, R, Q + 1, C4, S, DS4, S, F4, S, G4, S,
    F4, S, G4, S, C4, E, C4, S, DS4, S, F4, S,
    G4, S, F4, S, G4, S, AS4, E, AS4, S, A4, S,
    AS4, S, G4, S, F4, S, G4, S, C4, E, C4, S,
    DS4, S, F4, S, R, S, G4, S, R, S, A4, S,
    R, S, AS4, DE - 1
    );
    return t;
  }

  @Override
  public Track getBass() {
    Track t = new Track().withDefaults(BASS_VOL, BASS_DUTY);
    t.addNotes(
    F4, S, DS4, S, C4, S, AS3, S, C4, S, AS3, S,
    GS3, S, G3, S, GS3, S, G3, S, F3, S, DS3, S,
    F3, S, C3, S, DS3, S, E3, S, C3, S, AS2, S,
    C3, S, F2, DE, GS2, S, AS2, S, C3, S, AS2, S,
    C3, S, DS3, DE, D3, S, DS3, S, C3, S, AS2, S,
    C3, S, F2, E, GS2, S, AS2, S, C3, S, R, S,
    DS3, S, D3, S, DS3, S, D3, DE, AS2, S, C3, S,
    AS2, S, C3, S, F2, DE, GS2, S, AS2, S, C3, S,
    AS2, S, C3, S, DS3, DE, D3, S, DS3, S, C3, S,
    AS2, S, C3, S, F2, E, GS2, S, AS2, S, C3, S,
    R, S, DS3, S, D3, S, DS3, S, D3, DE, AS2, S,
    C3, S, AS2, S, C3, S, F2, DE, GS2, S, AS2, S,
    C3, S, AS2, S, C3, S, DS3, DE, D3, S, DS3, S,
    C3, S, AS2, S, C3, S, F2, E, GS2, S, AS2, S,
    C3, S, R, S, DS3, S, D3, S, DS3, S, D3, DE,
    AS2, S, C3, S, AS2, S, C3, S, F2, DE, GS2, S,
    AS2, S, C3, S, AS2, S, C3, S, DS3, DE, D3, S,
    DS3, S, C3, S, AS2, S, C3, S, F2, E, GS2, S,
    AS2, S, C3, S, R, S, DS3, S, D3, S, DS3, S,
    D3, DE, AS2, S, C3, Q, D3, DE, DS3, E, C3, S,
    G3, E, AS3, S + 2, B3, S + 2, C4, S + 2, D3, Q, DS3, DE,
    F3, Q, DS3, S, F3, Q, C3, Q, D3, DE, DS3, E,
    C3, S, G3, E, AS3, S + 2, B3, S + 2, C4, S + 2, D3, Q,
    DS3, DE, F3, 30, AS3, Q, G4, S, F4, S, D5, S,
    C5, S, AS4, S, A4, S, G4, S, F4, S, G4, S,
    F4, S, D4, S, C4, S, D4, S, C4, S, AS3, S,
    A3, S, C3, Q, D3, DE, DS3, S, C3, S + 2, D3, S + 2,
    DS3, S + 2, G2, S + 2, AS2, S + 2, B2, S + 2, C3, Q, D3, Q,
    DS3, DE, F3, DE, G3, E, F3, H, AS2, H, DS3, H,
    G2, Q, F2, S, A2, S, AS2, S, B2, S, C3, W,
    DS3, W, F3, H, AS2, H, DS3, 30, F3, E, DS3, S,
    G3, Q, F3, Q, G3, DH, F3, Q, DS3, DH, F3, Q,
    G3, DH, F3, Q, DS3, Q, R, S, DS3, S, F3, S,
    G3, S, A3, S, AS3, S, A3, E, F3, Q, G3, DH,
    F3, Q, DS3, DH, F3, Q, G3, DH, AS3, Q, F3, 60,
    R, 228, C3, S, AS2, S, C3, S, F2, DE, GS2, S,
    AS2, S, C3, S, AS2, S, C3, S, DS3, DE, D3, S,
    DS3, S, C3, S, AS2, S, C3, S, F2, E, GS2, S,
    AS2, S, C3, S, R, S, DS3, S, D3, S, DS3, S,
    D3, DE, AS2, S, C3, S, AS2, S, C3, S, F2, DE,
    GS2, S, AS2, S, C3, S, AS2, S, C3, S, DS3, DE,
    D3, S, DS3, S, C3, S, AS2, S, C3, S, F2, E,
    GS2, S, AS2, S, C3, S, R, S, DS3, S, D3, S,
    DS3, S, D3, DE, AS2, S, C3, S, AS2, S, C3, S,
    F2, DE, GS2, S, AS2, S, C3, S, AS2, S, C3, S,
    DS3, DE, D3, S, DS3, S, C3, S, AS2, S, C3, S,
    F2, E, GS2, S, AS2, S, C3, S, R, S, DS3, S,
    D3, S, DS3, S, D3, DE, AS2, S, C3, S, AS2, S,
    C3, S, F2, DE, GS2, S, AS2, S, C3, S, AS2, S,
    C3, S, DS3, DE, D3, S, DS3, S, C3, S, AS2, S,
    C3, S, F2, E, GS2, S, AS2, S, C3, S, R, S,
    DS3, S, D3, S, DS3, S, D3, DE, AS2, S, C3, Q,
    D3, DE, DS3, E, C3, S, G3, E, AS3, S + 2, B3, S + 2,
    C4, S + 2, D3, Q, DS3, DE, F3, Q, DS3, S, F3, Q,
    C3, Q, D3, DE, DS3, E, C3, S, G3, E, AS3, S + 2,
    B3, S + 2, C4, S + 2, D3, Q, DS3, DE, F3, 30, AS3, Q,
    G4, S, F4, S, D5, S, C5, S, AS4, S, A4, S,
    G4, S, F4, S, G4, S, F4, S, D4, S, C4, S,
    D4, S, C4, S, AS3, S, A3, S, C3, Q, D3, DE,
    DS3, S, C3, S + 2, D3, S + 2, DS3, S + 2, G2, S + 2, AS2, S + 2,
    B2, S + 2, C3, Q, D3, Q, DS3, DE, F3, DE, G3, E,
    F3, H, AS2, H, DS3, H, G2, Q, F2, S, A2, S,
    AS2, S, B2, S, C3, W, DS3, W, F3, H, AS2, H,
    DS3, 30, F3, E, DS3, S, G3, Q, F3, Q, G3, DH,
    F3, Q, DS3, DH, F3, Q, G3, DH, F3, Q, DS3, Q,
    R, S, DS3, S, F3, S, G3, S, A3, S, AS3, S,
    A3, E, F3, Q, G3, DH, F3, Q, DS3, DH, F3, Q,
    G3, DH, AS3, Q, F3, 60, R, 228, C3, S, AS2, S,
    C3, S, F2, DE, GS2, S, AS2, S, C3, S, AS2, S,
    C3, S, DS3, DE, D3, S, DS3, S, C3, S, AS2, S,
    C3, S, F2, E, GS2, S, AS2, S, C3, S, R, S,
    DS3, S, D3, S, DS3, S, D3, DE, AS2, S, C3, S,
    AS2, S, C3, S, F2, DE, GS2, S, AS2, S, C3, S,
    AS2, S, C3, S, DS3, DE, D3, S, DS3, S, C3, S,
    AS2, S, C3, S, F2, E, GS2, S, AS2, S, C3, S,
    R, S, DS3, S, D3, S, DS3, S, D3, DE, AS2, S,
    C3, S, AS2, S, C3, S, F2, DE, GS2, S, AS2, S,
    C3, S, AS2, S, C3, S, DS3, DE, D3, S, DS3, S,
    C3, S, AS2, S, C3, S, F2, E, GS2, S, AS2, S,
    C3, S, R, S, DS3, S, D3, S, DS3, S, D3, DE,
    AS2, S, C3, S, AS2, S, C3, S, F2, DE, GS2, S,
    AS2, S, C3, S, AS2, S, C3, S, DS3, DE, D3, S,
    DS3, S, C3, S, AS2, S, C3, S, F2, E, GS2, S,
    AS2, S, C3, S, R, S, DS3, S, D3, S, DS3, S,
    D3, DE, AS2, S, C3, Q, D3, DE, DS3, E, C3, S,
    G3, E, AS3, S + 2, B3, S + 2, C4, S + 2, D3, Q, DS3, DE,
    F3, Q, DS3, S, F3, Q, C3, Q, D3, DE, DS3, E,
    C3, S, G3, E, AS3, S + 2, B3, S + 2, C4, S + 2, D3, Q,
    DS3, DE, F3, 30, AS3, Q, G4, S, F4, S, D5, S,
    C5, S, AS4, S, A4, S, G4, S, F4, S, G4, S,
    F4, S, D4, S, C4, S, D4, S, C4, S, AS3, S,
    A3, S, C3, Q, D3, DE, DS3, S, C3, S + 2, D3, S + 2,
    DS3, S + 2, G2, S + 2, AS2, S + 2, B2, S + 2, C3, Q, D3, Q,
    DS3, DE, F3, DE, G3, E, F3, H, AS2, H, DS3, H,
    G2, Q, F2, S, A2, S, AS2, S, B2, S, C3, W,
    DS3, W, F3, H, AS2, H, DS3, 30, F3, E, DS3, S,
    G3, Q, F3, Q, G3, DH, F3, Q, DS3, DH, F3, Q,
    G3, DH, F3, Q, DS3, Q, R, S, DS3, S, F3, S,
    G3, S, A3, S, AS3, S, A3, E, F3, Q, G3, DH,
    F3, Q, DS3, DH, F3, Q, G3, DH, AS3, Q, F3, 60,
    R, 228, C3, S, AS2, S, C3, S, F2, DE, GS2, S,
    AS2, S, C3, S, AS2, S, C3, S, DS3, DE, D3, S,
    DS3, S, C3, S, AS2, S, C3, S, F2, E, GS2, S,
    AS2, S, C3, S, R, S, DS3, S, D3, S, DS3, S,
    D3, DE, AS2, S, C3, S, AS2, S, C3, S, F2, DE,
    GS2, S, AS2, S, C3, S, AS2, S, C3, S, DS3, DE,
    D3, S, DS3, S, C3, S, AS2, S, C3, S, F2, E,
    GS2, S, AS2, S, C3, S, R, S, DS3, S, D3, S,
    DS3, S, D3, DE, AS2, S, C3, S, AS2, S, C3, S,
    F2, DE, GS2, S, AS2, S, C3, S, AS2, S, C3, S,
    DS3, DE, D3, S, DS3, S, C3, S, AS2, S, C3, S,
    F2, E, GS2, S, AS2, S, C3, S, R, S, DS3, S,
    D3, S, DS3, S, D3, DE, AS2, S, C3, S, AS2, S,
    C3, S, F2, DE, GS2, S, AS2, S, C3, S, AS2, S,
    C3, S, DS3, DE, D3, S, DS3, S, C3, S, AS2, S,
    C3, S, F2, E, GS2, S, AS2, S, C3, S, R, S,
    DS3, S, D3, S, DS3, S, D3, DE, AS2, S, C3, Q,
    D3, DE, DS3, E, C3, S, G3, E, AS3, S + 2, B3, S + 2,
    C4, S + 2, D3, Q, DS3, DE, F3, Q, DS3, S, F3, Q,
    C3, Q, D3, DE, DS3, E, C3, S, G3, E, AS3, S + 2,
    B3, S + 2, C4, S + 2, D3, Q, DS3, DE, F3, 30, AS3, Q,
    G4, S, F4, S, D5, S, C5, S, AS4, S, A4, S,
    G4, S, F4, S, G4, S, F4, S, D4, S, C4, S,
    D4, S, C4, S, AS3, S, A3, S, C3, Q, D3, DE,
    DS3, S, C3, S + 2, D3, S + 2, DS3, S + 2, G2, S + 2, AS2, S + 2,
    B2, S + 2, C3, Q, D3, Q, DS3, DE, F3, DE, G3, E,
    F3, H, AS2, H, DS3, H, G2, Q, F2, S, A2, S,
    AS2, S, B2, S, C3, W, DS3, W, F3, H, AS2, H,
    DS3, 30, F3, E, DS3, S, G3, Q, F3, Q, G3, DH,
    F3, Q, DS3, DH, F3, Q, G3, DH, F3, Q, DS3, Q,
    R, S, DS3, S, F3, S, G3, S, A3, S, AS3, S,
    A3, E, F3, Q, G3, DH, F3, Q, DS3, DH, F3, Q,
    G3, DH, AS3, Q, F3, 60, R, 227
    );
    return t;
  }

  @Override
  public Track getDrums() {
    // Contra's groove is load-bearing, and the dedicated snare/tom voices are
    // velocity-driven, so hit them hard (0.9) to push the backbeat forward.
    // (KICK ignores this and always plays full via KickVoice.)
    Track t = new Track().withDefaults(0.9, DRUM_DUTY);
    t.addNotes(
    R, W, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, Q - T, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, DS, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, Q - T, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, DS, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, T, KICK, T,
    R, DS, KICK, T, R, T, SNARE, T, R, T, KICK, T,
    R, DS, KICK, T, R, T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, SNARE, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, Q - T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, DS, KICK, T, R, E + T, KICK, T,
    R, E + T, SNARE, T, R, DS, KICK, T, R, Q - T, KICK, T,
    R, DS, SNARE, T, R, DS, KICK, T, R, E + T, KICK, T,
    R, E + T, SNARE, T, R, DS, KICK, T, R, DS, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, SNARE, T, R, DS, KICK, T, R, E + T, KICK, T,
    R, E + T, SNARE, T, R, DS, KICK, T, R, Q - T, KICK, T,
    R, DS, SNARE, T, R, DS, KICK, T, R, E + T, KICK, T,
    R, E + T, SNARE, T, R, DS, KICK, T, R, DS, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, T, KICK, T, R, DS, KICK, T, R, T, SNARE, T,
    R, T, KICK, T, R, DS, KICK, T, R, T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
    R, E + T, KICK, T, R, E + T, SNARE, T, R, DS, KICK, T,
    R, Q - T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
    R, E + T, KICK, T, R, E + T, SNARE, T, R, DS, KICK, T,
    R, DS, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, SNARE, T, R, DS, KICK, T,
    R, E + T, KICK, T, R, E + T, SNARE, T, R, DS, KICK, T,
    R, Q - T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
    R, E + T, KICK, T, R, E + T, SNARE, T, R, DS, KICK, T,
    R, DS, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, T, KICK, T, R, DS, KICK, T,
    R, T, SNARE, T, R, T, KICK, T, R, DS, KICK, T,
    R, T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, SNARE, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, Q - T, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, DS, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, Q - T, KICK, T, R, DS, SNARE, T,
    R, DS, KICK, T, R, E + T, KICK, T, R, E + T, SNARE, T,
    R, DS, KICK, T, R, DS, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, T, KICK, T,
    R, DS, KICK, T, R, T, SNARE, T, R, T, KICK, T,
    R, DS, KICK, T, R, T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, E + T, KICK, T,
    R, T, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, E + T, KICK, T, R, T, SNARE, T,
    R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
    R, Q - T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
    R, Q - T, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, E + T, KICK, T, R, T, SNARE, T, R, DS, KICK, T,
    R, DS, KICK, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, Q - T, SNARE, T,
    R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
    R, DS, SNARE, T, R, Q - T, SNARE, T, R, Q - T, KICK, T,
    R, Q - T, KICK, T, R, Q - T, KICK, T, R, Q - T, KICK, T,
    R, Q - T, SNARE, T, R, Q - T, KICK, T, R, Q - T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, T, C3, T, R, T, C3, T,
    R, T, C3, T, R, 2
    );
    return t;
  }
}
