/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package javarominoes.model.music.song;

import chiptunesynth.ChiptuneSong;
import chiptunesynth.Track;

/**
 * Generated from Flashman.mid (Mega Man 2, by Takashi Tateishi) MIDI arranged
 * by Steven C. King; converted to ChiptuneSynth format. Uses constants from
 * ChiptuneSong interface. Non-standard durations (humanization
 * micro-articulations from the source MIDI) are expressed as arithmetic against
 * the named constants - e.g. H - 1 means "half note minus 1 frame" which gives
 * a tiny breath before the next note.
 *
 * @author dylan
 */
public class FlashmanSong implements ChiptuneSong {
  
  @Override
  public Track getLead() {
    Track t = new Track().withDefaults(LEAD_VOL, LEAD_DUTY);
    // Flashman's drums already swing (4-voice kit + humanized micro-timing);
    // the lead was the one flat voice. Its phrases land on sustained targets
    // (E4/H, D5/W-2, CS5/H, C5/H) — give those the singing wobble while the
    // sixteenth-and-eighth filigree stays clean under the 12-frame delay.
    t.withVibrato(0.3, 5.5, 12);
    t.addNotes(
            R, H + E, E3, Q, G3, S, R, S, B3, S, R, S,
            D4, DE, CS4, DE, A3, E, C4, DE, B3, DE, G3, E,
            A3, S, R, S, G3, S, R, S, E3, S, D3, E,
            E3, S, FS4, DE, G4, S, R, E, FS4, DE, G4, S,
            R, DQ, FS4, DE, G4, S, R, S, B4, S, R, S,
            B4, S, A4, S, R, S, G4, S, R, S, FS4, E,
            R, E, E3, Q, G3, S, R, S, B3, S, R, S,
            D4, DE, CS4, DE, A3, E, C4, DE, B3, DE, G3, E,
            A3, S, R, S, G3, S, R, S, E3, S, D3, E,
            E3, S, FS4, DE, G4, S, R, E, FS4, DE, G4, S,
            R, DQ, FS4, DE, G4, S, R, S, B4, S, R, S,
            B4, S, A4, S, R, S, G4, S, R, S, FS4, E,
            R, E, E3, Q, G3, S, R, S, B3, S, R, S,
            D4, DE, CS4, DE, A3, E, C4, DE, B3, DE, G3, E,
            A3, S, R, S, G3, S, R, S, E3, S, D3, E,
            E3, S, FS4, DE, G4, S, R, E, FS4, DE, G4, S,
            R, DQ, FS4, DE, G4, S, R, S, B4, S, R, S,
            B4, S, A4, S, R, S, G4, S, R, S, FS4, E,
            R, E, E3, Q, G3, S, R, S, B3, S, R, S,
            D4, DE, CS4, DE, A3, E, C4, DE, B3, DE, G3, E,
            A3, S, R, S, G3, S, R, S, E3, S, D3, E,
            E3, S, FS4, DE, G4, S, R, E, FS4, DE, G4, S,
            R, Q, A4, E, R, S, A4, S, R, S, A4, S,
            R, S, A4, S, B4, Q, R, DQ, E4, E, B4, E,
            A4, E, B4, Q, A4, E, G4, E, A4, E, B4, E,
            R, E, E4, H - 1, R, 1, G4, E, FS4, E, R, E,
            FS4, E, R, E, FS4, E, E4, E, D4, E, E4, H + E - 1,
            R, E + 1, E4, E, G4, E, A4, E, R, E, E4, E,
            B4, E, A4, E, B4, Q, A4, E, G4, E, A4, E,
            B4, E, R, E, E4, H - 1, R, 1, G4, E, FS4, E,
            R, E, FS4, E, R, E, G4, E, A4, E, FS4, E,
            E4, H + E - 1, R, E + 1, E4, E, G4, E, B4, E, D5, W - 2,
            R, 2, CS5, H - 1, R, 1, C5, H - 1, R, 1, G4, E,
            E4, DQ - 1, R, E + 1, E4, E, G4, E, A4, E, AS4, E,
            B4, E, AS4, E, B4, E, A4, E, G4, E, E4, E,
            D4, E, D5, W - 2, R, 2, CS5, H - 1, R, 1, C5, H - 1,
            R, 1, G4, E, E4, DQ - 1, R, E + 1, E4, E, G4, E,
            A4, E, E5, E, B4, DQ, DS5, E, FS5, E, A5, E,
            B5, E, R, E, E4, E, B4, E, A4, E, B4, Q,
            A4, E, G4, E, A4, E, B4, E, R, E, E4, H - 1,
            R, 1, G4, E, FS4, E, R, E, FS4, E, R, E,
            FS4, E, E4, E, D4, E, E4, H + E - 1, R, E + 1, E4, E,
            G4, E, A4, E, R, E, E4, E, B4, E, A4, E,
            B4, Q, A4, E, G4, E, A4, E, B4, E, R, E,
            E4, H - 1, R, 1, G4, E, FS4, E, R, E, FS4, E,
            R, E, G4, E, A4, E, FS4, E, E4, H + E - 1, R, E + 1,
            E4, E, G4, E, B4, E, D5, W - 2, R, 2, CS5, H - 1,
            R, 1, C5, H - 1, R, 1, G4, E, E4, DQ - 1, R, E + 1,
            E4, E, G4, E, A4, E, AS4, E, B4, E, AS4, E,
            B4, E, A4, E, G4, E, E4, E, D4, E, D5, W - 2,
            R, 2, CS5, H - 1, R, 1, C5, H - 1, R, 1, G4, E,
            E4, DQ - 1, R, E + 1, E4, E, G4, E, A4, E, E5, E,
            B4, DQ, DS5, E, FS5, E, A5, E, B5, E, R, E,
            E4, E, B4, E, A4, E, B4, Q, A4, E, G4, E,
            A4, E, B4, E, R, E, E4, H - 1, R, 1, G4, E,
            FS4, E, R, E, FS4, E, R, E, FS4, E, E4, E,
            D4, E, E4, H + E - 1, R, E + 1, E4, E, G4, E, A4, E
    );
    return t;
  }

  @Override
  public Track getHarmony() {
    Track t = new Track().withDefaults(HARMONY_VOL, HARMONY_DUTY);
    t.addNotes(
            R, H, E3, Q - 1, R, 1, G3, S, R, S, B3, S,
            R, S, D4, DE - 1, R, 1, CS4, DE - 1, R, 1, A3, E,
            C4, DE - 1, R, 1, B3, DE - 1, R, 1, G3, E, A3, S,
            R, S, G3, S, R, S, E3, S, D3, E, E3, S,
            R, E, D4, DE, E4, S, R, E, D4, DE, E4, S,
            R, DQ, D4, DE, E4, S, R, S, G4, S, R, S,
            G4, S, FS4, S, R, S, E4, S, R, S, D4, E,
            E3, Q - 1, R, 1, G3, S, R, S, B3, S, R, S,
            D4, DE - 1, R, 1, CS4, DE - 1, R, 1, A3, E, C4, DE - 1,
            R, 1, B3, DE - 1, R, 1, G3, E, A3, S, R, S,
            G3, S, R, S, E3, S, D3, E, E3, S, R, E,
            D4, DE, E4, S, R, E, D4, DE, E4, S, R, DQ,
            D4, DE, E4, S, R, S, G4, S, R, S, G4, S,
            FS4, S, R, S, E4, S, R, S, D4, E, E3, Q - 1,
            R, 1, G3, S, R, S, B3, S, R, S, D4, DE - 1,
            R, 1, CS4, DE - 1, R, 1, A3, E, C4, DE - 1, R, 1,
            B3, DE - 1, R, 1, G3, E, A3, S, R, S, G3, S,
            R, S, E3, S, D3, E, E3, S, R, E, D4, DE,
            E4, S, R, E, D4, DE, E4, S, R, DQ, D4, DE,
            E4, S, R, S, G4, S, R, S, G4, S, FS4, S,
            R, S, E4, S, R, S, D4, E, E3, Q - 1, R, 1,
            G3, S, R, S, B3, S, R, S, D4, DE - 1, R, 1,
            CS4, DE - 1, R, 1, A3, E, C4, DE - 1, R, 1, B3, DE - 1,
            R, 1, G3, E, A3, S, R, S, G3, S, R, S,
            E3, S, D3, E, E3, S, R, E, D4, DE, E4, S,
            R, E, D4, DE, E4, S, R, Q, FS4, E, R, S,
            FS4, S, R, S, FS4, S, R, S, FS4, S, G4, Q - 1,
            R, Q + 1, G4, S, A4, S, R, S, G4, S, R, S,
            G4, S, A4, S, G4, S, FS4, S, G4, S, R, S,
            FS4, S, R, S, FS4, S, G4, S, FS4, S, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            D4, S, E4, S, R, S, E4, S, R, S, D4, S,
            E4, E, G4, S, A4, S, R, S, G4, S, R, S,
            G4, S, A4, S, G4, S, FS4, S, G4, S, R, S,
            FS4, S, R, S, FS4, S, G4, S, FS4, S, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            D4, S, E4, S, R, S, E4, S, R, S, D4, S,
            E4, E, G4, S, A4, S, R, S, G4, S, R, S,
            G4, S, A4, S, G4, S, FS4, S, G4, S, R, S,
            FS4, S, R, S, FS4, S, G4, S, FS4, S, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            D4, S, E4, S, R, S, E4, S, R, S, D4, S,
            E4, E, G4, S, A4, S, R, S, G4, S, R, S,
            G4, S, A4, S, G4, S, FS4, S, G4, S, R, S,
            FS4, S, R, S, FS4, S, G4, S, FS4, S, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            D4, S, E4, S, R, S, E4, S, R, S, D4, S,
            E4, E, B4, W - T, R, T, AS4, H - 2, R, 2, A4, H - 2,
            R, E + 2, G4, E, A4, E, G4, E, B4, E, G4, E,
            R, E, G4, E, A4, E, G4, E, B4, E, G4, E,
            R, E, G4, E, FS4, E, G4, E, B4, W - T, R, T,
            AS4, H - 2, R, 2, A4, H - 2, R, E + 2, G4, E, A4, E,
            G4, E, B4, E, G4, E, R, E, G4, E, A4, E,
            G4, E, B4, E, G4, E, R, E, G4, E, FS4, E,
            G4, DE, A4, S, R, S, G4, S, R, S, G4, S,
            A4, S, G4, S, FS4, S, G4, S, R, S, FS4, S,
            R, S, FS4, S, G4, S, FS4, S, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            G4, S, A4, S, R, S, G4, S, R, S, G4, S,
            A4, S, G4, S, FS4, S, G4, S, R, S, FS4, S,
            R, S, FS4, S, G4, S, FS4, S, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            G4, S, A4, S, R, S, G4, S, R, S, G4, S,
            A4, S, G4, S, FS4, S, G4, S, R, S, FS4, S,
            R, S, FS4, S, G4, S, FS4, S, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            G4, S, A4, S, R, S, G4, S, R, S, G4, S,
            A4, S, G4, S, FS4, S, G4, S, R, S, FS4, S,
            R, S, FS4, S, G4, S, FS4, S, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E, D4, S,
            E4, S, R, S, E4, S, R, S, D4, S, E4, E,
            B4, W - T, R, T, AS4, H - 2, R, 2, A4, H - 2, R, E + 2,
            G4, E, A4, E, G4, E, B4, E, G4, E, R, E,
            G4, E, A4, E, G4, E, B4, E, G4, E, R, E,
            G4, E, FS4, E, G4, E, B4, W - T, R, T, AS4, H - 2,
            R, 2, A4, H - 2, R, E + 2, G4, E, A4, E, G4, E,
            B4, E, G4, E, R, E, G4, E, A4, E, G4, E,
            B4, E, G4, E, R, E, G4, E, FS4, E, G4, DE,
            A4, S, R, S, G4, S, R, S, G4, S, A4, S,
            G4, S, FS4, S, G4, S, R, S, FS4, S, R, S,
            FS4, S, G4, S, FS4, S, D4, S, E4, S, R, S,
            E4, S, R, S, D4, S, E4, E, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E, G4, S,
            A4, S, R, S, G4, S, R, S, G4, S, A4, S,
            G4, S, FS4, S, G4, S, R, S, FS4, S, R, S,
            FS4, S, G4, S, FS4, S, D4, S, E4, S, R, S,
            E4, S, R, S, D4, S, E4, E, D4, S, E4, S,
            R, S, E4, S, R, S, D4, S, E4, E
    );
    return t;
  }

  @Override
  public Track getBass() {
    Track t = new Track().withDefaults(BASS_VOL, BASS_DUTY);
    t.addNotes(
            R, H, E2, Q - 1, R, 1, G2, S, R, S, B2, S,
            R, S, D3, DE - 1, R, 1, CS3, DE - 1, R, 1, A2, E,
            C3, DE - 1, R, 1, B2, DE - 1, R, 1, G2, E, A2, S,
            R, S, G2, S, R, S, E2, S, D2, E, E2, S,
            R, E, E2, DE, R, S, E2, DE, R, S, E2, DE,
            R, S, E2, DE, R, S, E2, E, FS2, S, R, S,
            FS2, E, G2, S, R, S, B2, S, R, S, D2, Q - 1,
            R, 1, E2, Q - 1, R, 1, G2, S, R, S, B2, S,
            R, S, D3, DE - 1, R, 1, CS3, DE - 1, R, 1, A2, E,
            C3, DE - 1, R, 1, B2, DE - 1, R, 1, G2, E, A2, S,
            R, S, G2, S, R, S, E2, S, D2, E, E2, S,
            R, E, E2, DE, R, S, E2, DE, R, S, E2, DE,
            R, S, E2, DE, R, S, E2, E, FS2, S, R, S,
            FS2, E, G2, S, R, S, B2, S, R, S, D2, Q - 1,
            R, 1, E2, Q - 1, R, 1, G2, S, R, S, B2, S,
            R, S, D3, DE - 1, R, 1, CS3, DE - 1, R, 1, A2, E,
            C3, DE - 1, R, 1, B2, DE - 1, R, 1, G2, E, A2, S,
            R, S, G2, S, R, S, E2, S, D2, E, E2, S,
            R, E, E2, DE, R, S, E2, DE, R, S, E2, DE,
            R, S, E2, DE, R, S, E2, E, FS2, S, R, S,
            FS2, E, G2, S, R, S, B2, S, R, S, D2, Q - 1,
            R, 1, E2, Q - 1, R, 1, G2, S, R, S, B2, S,
            R, S, D3, DE - 1, R, 1, CS3, DE - 1, R, 1, A2, E,
            C3, DE - 1, R, 1, B2, DE - 1, R, 1, G2, E, A2, S,
            R, S, G2, S, R, S, E2, S, D2, E, E2, S,
            R, E, E2, DE, R, S, E2, DE, R, S, E2, DE,
            R, S, E2, E, D2, E, R, S, D2, S, R, S,
            D2, S, R, S, D2, S, E2, S, R, E, E2, S,
            DS2, S, D2, S, CS2, S, C2, S, E2, Q, R, E,
            E2, DE, G2, S, R, S, B2, S, R, S, G2, S,
            E2, DQ, R, E, E2, DE, G2, S, R, S, B2, S,
            R, S, G2, S, E2, E, D2, Q, R, E, D2, DE,
            FS2, S, R, S, A2, S, R, S, FS2, S, D2, E,
            E2, Q, R, E, E2, DE, G2, S, R, S, B2, S,
            R, S, G2, S, E2, DQ, R, E, E2, DE, G2, S,
            R, S, B2, S, R, S, G2, S, E2, DQ, R, E,
            E2, DE, G2, S, R, S, B2, S, R, S, G2, S,
            E2, E, D2, Q, R, E, D2, DE, FS2, S, R, S,
            A2, S, R, S, FS2, S, D2, E, E2, Q, R, E,
            E2, DE, G2, S, R, S, B2, S, R, S, G2, S,
            E2, E, G2, S, R, S, G2, DE, R, S, G2, DE,
            R, S, G2, DE, R, S, G2, E, FS2, S, R, S,
            FS2, DE, R, S, FS2, E, F2, S, R, S, F2, DE,
            R, S, F2, E, R, E, E2, E, FS2, E, E2, E,
            G2, E, E2, E, R, E, E2, E, R, W, G2, S,
            R, S, G2, DE, R, S, G2, DE, R, S, G2, DE,
            R, S, G2, E, FS2, S, R, S, FS2, DE, R, S,
            FS2, E, F2, S, R, S, F2, DE, R, S, F2, E,
            R, E, E2, E, FS2, E, E2, E, G2, E, E2, E,
            R, E, E2, E, R, W, E2, Q, R, E, E2, DE,
            G2, S, R, S, B2, S, R, S, G2, S, E2, DQ,
            R, E, E2, DE, G2, S, R, S, B2, S, R, S,
            G2, S, E2, E, D2, Q, R, E, D2, DE, FS2, S,
            R, S, A2, S, R, S, FS2, S, D2, E, E2, Q,
            R, E, E2, DE, G2, S, R, S, B2, S, R, S,
            G2, S, E2, DQ, R, E, E2, DE, G2, S, R, S,
            B2, S, R, S, G2, S, E2, DQ, R, E, E2, DE,
            G2, S, R, S, B2, S, R, S, G2, S, E2, E,
            D2, Q, R, E, D2, DE, FS2, S, R, S, A2, S,
            R, S, FS2, S, D2, E, E2, Q, R, E, E2, DE,
            G2, S, R, S, B2, S, R, S, G2, S, E2, E,
            G2, S, R, S, G2, DE, R, S, G2, DE, R, S,
            G2, DE, R, S, G2, E, FS2, S, R, S, FS2, DE,
            R, S, FS2, E, F2, S, R, S, F2, DE, R, S,
            F2, E, R, E, E2, E, FS2, E, E2, E, G2, E,
            E2, E, R, E, E2, E, R, W, G2, S, R, S,
            G2, DE, R, S, G2, DE, R, S, G2, DE, R, S,
            G2, E, FS2, S, R, S, FS2, DE, R, S, FS2, E,
            F2, S, R, S, F2, DE, R, S, F2, E, R, E,
            E2, E, FS2, E, E2, E, G2, E, E2, E, R, E,
            E2, E, R, W, E2, Q, R, E, E2, DE, G2, S,
            R, S, B2, S, R, S, G2, S, E2, DQ, R, E,
            E2, DE, G2, S, R, S, B2, S, R, S, G2, S,
            E2, E, D2, Q, R, E, D2, DE, FS2, S, R, S,
            A2, S, R, S, FS2, S, D2, E, E2, Q, R, E,
            E2, DE, G2, S, R, S, B2, S, R, S, G2, S,
            E2, E
    );
    return t;
  }

  @Override
  public Track getDrums() {
    Track t = new Track().withDefaults(DRUM_VOL, DRUM_DUTY);
    t.addNotes(
            R, H, KICK, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, KICK, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, KICK, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, KICK, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, KICK, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, KICK, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, KICK, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, KICK, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, KICK, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, KICK, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, SNARE, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, KICK, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, KICK, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, SNARE, T, R, T, KICK, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, KICK, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, T, KICK, T, R, T, SNARE, T, R, T, HIHAT, T,
            R, T, KICK, T, R, T, HIHAT, T, R, T, SNARE, T,
            R, T, SNARE, T, R, DS, SNARE, T, R, DS, SNARE, T,
            R, DS, SNARE, T, R, T, SNARE, T, R, E + T, KICK, T,
            R, T, SNARE, T, R, T, SNARE, T, R, T, SNARE, T,
            R, T, SNARE, T, R, T, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, SNARE, T, R, T, SNARE, T,
            R, T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, SNARE, T, R, T, SNARE, T,
            R, T, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, SNARE, T, R, T, SNARE, T,
            R, T, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, SNARE, T, R, T, SNARE, T, R, T, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, SNARE, T, R, T, SNARE, T, R, T, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, CYMBAL, T, R, DS, KICK, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, CYMBAL, T,
            R, DS, CYMBAL, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, SNARE, T,
            R, DS, SNARE, T, R, T, SNARE, T, R, T, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS, KICK, T, R, Q - T, SNARE, T,
            R, E + T, HIHAT, T, R, T, HIHAT, T, R, T, HIHAT, T,
            R, T, KICK, T, R, DS, SNARE, T, R, DS, KICK, T,
            R, DS, KICK, T, R, Q - T, SNARE, T, R, E + T, HIHAT, T,
            R, T, HIHAT, T, R, T, HIHAT, T, R, T, KICK, T,
            R, DS, SNARE, T, R, DS, KICK, T, R, DS, KICK, T,
            R, Q - T, SNARE, T, R, E + T, HIHAT, T, R, T, HIHAT, T,
            R, T, HIHAT, T, R, T, KICK, T, R, DS, SNARE, T,
            R, DS, KICK, T, R, DS
    );
    return t;
  }
}
